dz-4/adaptive - верстка страницы компонент + адаптив лейаута
js-tasks-ru/htmlcss-20230411_sum2108 pull request #12
Opened 2023-05-03 17:02 UTC by xenomorfy

2023-05-03 17:03 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-04 14:26 UTC, GSemikozov requested changes

2023-05-04 14:26 UTC, GSemikozov commented on components/card/card.css
> +    padding: 38px;
не по макету

2023-05-04 14:26 UTC, GSemikozov commented on components/card/card.css
> +    height: 100%;
лишнее

2023-05-04 14:26 UTC, GSemikozov commented on components/card/card.css
> +    height: 100%;
точно ли без этого не обойтись?

2023-05-04 14:26 UTC, GSemikozov commented on components/card/card.css
> +        min-width: 164px;
тогда наверно проще зафиксировать (вряд ли нам понравится то как карта себя поведет если ширина будет больше, при таком разрешении)

2023-05-04 14:26 UTC, GSemikozov commented on components/card/card.css
> +@media screen and (max-width: 375px){
если перевернуть телефон - ширина экрана будет больше 600px. По этой причине рекомендуют начинать моб версию например с 767

2023-05-04 14:26 UTC, GSemikozov commented on components/header/header.css
> +.header_nav {
модификатор хедера или элемент? если элемент - .header__nav

2023-05-04 14:26 UTC, GSemikozov commented on components/header/header.css
> +.header_nav > a {
ошибка по БЭМ, вложенные селекторы и селекторы тегов не используем. Просто надо добавить класс на `<a>`

2023-05-04 14:26 UTC, GSemikozov commented on components/header/header.css
> +        position: absolute;
моб меню или меню десктопное? в любом случае если позиционируем через absolute, то надо указывать координаты top left и тд

2023-05-04 14:26 UTC, GSemikozov commented on components/histogram/histogram.css
> +    flex: 1;
лишнее

2023-05-04 14:26 UTC, GSemikozov commented on pages/main.html
> +              <div class="tooltip__block  block_active">
block_active -> tooltip__block_active?

2023-05-10 09:56 UTC, xenomorfy commented on components/header/header.css
> +.header_nav {
это элементы с самого первого задания для лейаута, убрал полностью

2023-05-10 09:56 UTC, xenomorfy commented on components/header/header.css
> +.header_nav > a {
это элементы с самого первого задания для лейаута, убрал полностью

2023-05-10 09:59 UTC, xenomorfy commented on components/header/header.css
> +        position: absolute;
его пока нет в верстке, уберу в след коммите (временно)

2023-05-10 10:03 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-11 14:51 UTC, GSemikozov requested changes

2023-05-11 14:51 UTC, GSemikozov commented on components/calendar/calendar.css
> +.calendar_preview {
почему паддинг?) видимо речь о .calendar_small? либо отступ относится к другому блоку куда встраиваемся?

2023-05-11 14:51 UTC, GSemikozov commented on components/card/card.css
> +    padding: 38px;
все еще актуально

2023-05-11 14:51 UTC, GSemikozov commented on components/card/card.css
> +        margin: 0 auto;
выравнивать через родителя (перевернем телефон в landscape и проверим)

2023-05-11 14:51 UTC, GSemikozov commented on components/card/card.css
> +    .card__description {
описание не надо скрывать

2023-05-11 15:00 UTC, xenomorfy commented on components/card/card.css
> +    padding: 38px;
исправил

2023-05-11 15:27 UTC, xenomorfy commented on components/card/card.css
> +        margin: 0 auto;
поправил

2023-05-15 16:26 UTC, xenomorfy commented on components/card/card.css
> +    .card__description {
ok

2023-05-16 07:56 UTC, GSemikozov approved these changes

2023-05-16 07:56 UTC, merged