dz-6/checkbox - чекбоксы и их состояния
js-tasks-ru/htmlcss-20230411_sum2108 pull request #17
Opened 2023-05-15 17:40 UTC by xenomorfy

2023-05-15 17:40 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-16 07:57 UTC, GSemikozov requested changes

2023-05-16 07:57 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +    display: flex;
inline-flex

2023-05-17 15:54 UTC, GSemikozov approved these changes

2023-05-17 15:54 UTC, merged