dz-6/radio - радио кнопки
js-tasks-ru/htmlcss-20230411_sum2108 pull request #18
Opened 2023-05-15 18:49 UTC by xenomorfy

2023-05-15 18:49 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-16 07:57 UTC, GSemikozov requested changes

2023-05-16 07:57 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +    display: flex;
inline-flex

2023-05-17 15:54 UTC, GSemikozov requested changes

2023-05-17 15:54 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +    display: flex;
не исправлено

2023-05-18 21:46 UTC, GSemikozov approved these changes

2023-05-18 21:46 UTC, merged