dz-6/toggler - тогглер
js-tasks-ru/htmlcss-20230411_sum2108 pull request #19
Opened 2023-05-15 19:34 UTC by xenomorfy

2023-05-15 19:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-16 08:12 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-05-16 08:15 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-05-17 15:51 UTC, GSemikozov requested changes

2023-05-17 15:51 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +    display: flex;
inline-flex

2023-05-17 17:27 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-17 17:28 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-05-18 21:46 UTC, GSemikozov approved these changes

2023-05-18 21:46 UTC, merged